language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -r requirements_dev.txt
script:
- travis_wait pytest tests/test_papi_iot.py
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: oLZPXwW005Uvh60I8RCEvYOqcblRVclGzUpWk9rkVwT0vSLcL8P18DPaSypcGtLz6mSun65WF5DHS4lrN5fgPvGeIBnpNKmOVnbvhq6RU6C6zvjfmx8lYZvqs1QkcLOP1tvwEJ6ZK26cC+e1MjQ0R56RitwGtvhMzJaMAcpBwvO4Lb2mSiHPLy+lnjJca0R6tsPwb9hHsXcf0aO8W/o5NS25+Et3w7zdPt44m6UqsXQFvWuesm1YPUV+DrtNZzCvNzR4GhdWPI9BlAuTOgGLxec7mychZ3vLdqra8sqWvs4rg+phcEODZ33c5yq8FavaNG15s8zYZJygs5GYSOm7toIz2epSS43j0cGQ2OzeeRPlhddrB4fUatMzHbJ4pRfRFBA9pGoSY74RbiEgIqLp1N0SqP7QujdvwtluFELevEi6lVtWbnHUu4Y/rB61CTlSAM/R6/tMUdZqs4uDW6V1w/nWq6aH3Gz9fdRUV5DknhJDLxf5t5YkJeB+UafkEp5a/ir436j6/NKHn7w9aam6tbsK9Qv8wivAvnwjvoy6PJOXsdyBvh3dIEV/NF01fqunAlyPAHChWJMBE9iH4YP84uMq4iAQ5Eoe5aBbYgE+ghmzzX5rId2OuV8BntJAonewRTSzMc+GxxJZTScS3hEUg8ZyDQrxu6MAKeJdPnTHXz0=
  on:
    tags: true
    repo: Stelele/papi_iot
    python: 3.8
