language: python
python:
- 3.8
- 3.7
- 3.6
install:
- pip install -r requirements_dev.txt
script:
- travis_wait pytest tests/test_papi_iot.py
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password: pypi-AgEIcHlwaS5vcmcCJGVhNWU3YTZhLTQ5NmQtNDY4Yi1iOGRjLTA5Y2I2OTExNjNjOAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgO_frszCe6ZpqfuLzJYynoJf5EiYPx8es3yAbWBUKT4A
  on:
    tags: true
    repo: Stelele/papi_iot
    python: 3.8
